export default {
  transition: 'scale',
  loadingTransition: 'fade',
  appear: false,
  overlay: true,
  layout: true,
  fullscreen: false,
  persistent: false,
  scrollLock: true,
  closeOnOverlay: true,
  closeOnEscape: true,
  noPadding: false,
  noRadius: false,
  focusableElement: null,
  zIndex: 1000,
  mountTo: 'body',
  import: (name) => import(`@/components/${name}.vue`),
};
